### ISSUE TITLE
No build machine ferguson4k kernel.bin for image sdcard

### ISSUE THREAD

**Issue by norhap** [PLi-metas/meta-dinobot#6]
machine= ferguson4k does not build good linux 4.4.35 (size kernel.bin of 5.7 Mb) (I can not start image in sdcard)
log build:

> QA issue files/directories /tmp/uImage

machine dinobot4kse work [OK]. (kernel.bin 7.7 Mb) start image in sdcard.

**Comment by persianpros** [comment]
Update and try again I think it's ok now.
